#!/bin/sh

COSMO=${COSMO:-/opt/cosmo}
COSMOS=${COSMOS:-/opt/cosmos}
ARCH=${ARCH:-x86_64}

OBJCOPY="$COSMO/cosmocc/bin/$ARCH-unknown-cosmo-objcopy"
FIXUPOBJ="$COSMO/o/tool/build/fixupobj.com"
ZIPCOPY="$COSMO/o/tool/build/zipcopy.com"

if [ ! -f "$1" ]; then
  echo "no file to apecopy!"
  exit 1
fi

SRC="$1"
DST="${2:-$1.com}"

"$OBJCOPY" -S -O binary "$SRC" "$DST" || exit
"$ZIPCOPY" "$SRC" "$DST" || exit
