#define ARROW_VERSION 1
#define ARROW_VERSION_MINOR 1
#define ARROW_VERSION_PATCH 1
#define ARROW_VERSION_MAJOR 1
#define ARROW_VERSION_STRING "1.1.1"

#define ARROW_SO_VERSION "1.1"
#define ARROW_FULL_SO_VERSION "1.1.1"
#define ARROW_CXX_COMPILER_ID "gcc"
#define ARROW_CXX_COMPILER_VERSION "12"
#define ARROW_CXX_COMPILER_FLAGS ""
#define ARROW_GIT_ID "master"
#define ARROW_GIT_DESCRIPTION ""
#define ARROW_PACKAGE_KIND "source"
#define ARROW_BUILD_TYPE "cosmo"
